### ISSUE TITLE
Swithc to already installed conda environments

### ISSUE THREAD

**Issue by gkourogiorgas** [jupyterlab/jupyterlab-desktop#277] opened 2021-10-04 11:23 UTC
I installed Jupyterlab desktop app and I want to use my existing conda (or even venv, pyenv etc) envs. When I used jupyterlab in the browser I would either install it in the different envs or better install an extension that would read the envs and let me choose the one I want for each kernel and hence each notebook. 

I understand that extensions are not enabled, correct?

Is there a work-around for the multiple envs locally?

**Comment by hereiskunalverma** [comment] 2021-10-05 03:16
I think you can use the inbuilt environment selection tab in jupyterlab app.
Follow the link : https://stackoverflow.com/questions/37085665/in-which-conda-environment-is-jupyter-executing

**Comment by krassowski** [comment] 2021-10-06 14:05
Does this help: https://github.com/jupyterlab/jupyterlab_app/issues/169#issuecomment-934708235? It looks like a duplicate of #169, could we close this one to avoid a deluge of issues?

**Comment by shayandavoodii** [comment] 2021-11-20 17:41
Instructions for Windows : https://github.com/jupyterlab/jupyterlab-desktop/issues/169#issuecomment-969944168

**Comment by krassowski** [comment] 2021-11-20 19:45
JupyterLab Desktop [v3.2.3-1](https://github.com/jupyterlab/jupyterlab-desktop/releases/tag/v3.2.3-1) added support for changing environments from the GUI (a selector on the status bar), including using a custom conda environment.

The instructions are currently available in the user guide: https://github.com/jupyterlab/jupyterlab-desktop/blob/master/user-guide.md#changing-the-python-environment-used-by-jupyterlab-desktop

I will close this one as resolved.

**Closed by krassowski** 2021-11-20 19:45 UTC
Labels: enhancement
