### ISSUE TITLE
Jupyter Server Initialization Failed

### ISSUE THREAD

**Issue by monomycelium** [jupyterlab/jupyterlab-desktop#381] opened 2021-12-23 13:25 UTC
I downloaded JupyterLab by following the recommended options and steps. When I launched the application, this showed:

![Issue](https://user-images.githubusercontent.com/95113443/147246602-e2614f50-72be-409b-89c4-306e34e5eaf6.png)

I tried launching the application again but the issue persisted. I uninstalled both the application and the server application and installed it again, but the same thing happened.

More information:
- Operating System and version: Windows 10 Pro (21H2) (Build 19044.1415)
- JupyterLab-Desktop version: 3.2.5-2
- Installer: .exe

Here is the log:
[main.log](https://github.com/jupyterlab/jupyterlab-desktop/files/7769521/main.log)

I hope this issue can be resolved soon as I cannot wait to try out this amazing application!

**Comment by krassowski** [comment] 2021-12-23 13:41
Thank you for reporting this issue. The log file includes the following:

```python
[2021-12-23 20:46:54.243] [info]  Jupyter Server initialization message: Traceback (most recent call last):
  File "C:\JupyterLab\resources\jlab_server\lib\runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\JupyterLab\resources\jlab_server\lib\runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\JupyterLab\resources\jlab_server\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\JupyterLab\resources\jlab_server\lib\site-packages\jupyterlab\__init__.py", line 7, in <module>
    from .labapp import LabApp
  File "C:\JupyterLab\resources\jlab_server\lib\site-packages\jupyterlab\labapp.py", line 15, in <module>
    from jupyter_server.serverapp import flags
  File "C:\JupyterLab\resources\jlab_server\lib\site-packages\jupyter_server\serverapp.py", line 42, in <module>
    from jupyter_server.utils import run_sync_in_loop, urljoin, pathname2url
  File "C:\JupyterLab\resources\jlab_server\lib\site-packages\jupyter_server\utils.py", line 23, in <module>
    from tornado.httpclient import AsyncHTTPClient
  File "C:\JupyterLab\resources\jlab_server\lib\site-packages\tornado\httpclient.py", line 42, in <module>
    import ssl
  File "C:\JupyterLab\resources\jlab_server\lib\ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: DLL load failed while importing _ssl: The specified module could not be found.
```

It looks like OpenSSL DLL issue on your Windows installation. This might happen when anaconda is installed locally rather than globally (did you install JupyterLab Desktop for all users, or just for you?), when DLLs are missing or not in path.

Could you please check if the workaround of copying the DLL as described in https://github.com/ContinuumIO/anaconda-issues/issues/11994 solves this issue for you? If yes, we could add a script to do that during installation.

Another issue is that we need to allow opening links to GitHub because it looks the button "Report issue" gets:

```
[2021-12-23 21:05:50.748] [warn]  Navigation is not allowed; attempted navigation to: https://github.com/login?return_to=%2Fjupyterlab%2Fjupyterlab-desktop%2Fissues%2Fnew
```

**Comment by marshlands2048** [comment] 2021-12-23 14:29
I downloaded it just for me. I will check out the link later. Thanks!

**Comment by eurekazheng** [comment] 2021-12-27 09:41
> Thank you for reporting this issue. The log file includes the following:
> 
> ```python
> [2021-12-23 20:46:54.243] [info]  Jupyter Server initialization message: Traceback (most recent call last):
>   File "C:\JupyterLab\resources\jlab_server\lib\runpy.py", line 185, in _run_module_as_main
>     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
>   File "C:\JupyterLab\resources\jlab_server\lib\runpy.py", line 144, in _get_module_details
>     return _get_module_details(pkg_main_name, error)
>   File "C:\JupyterLab\resources\jlab_server\lib\runpy.py", line 111, in _get_module_details
>     __import__(pkg_name)
>   File "C:\JupyterLab\resources\jlab_server\lib\site-packages\jupyterlab\__init__.py", line 7, in <module>
>     from .labapp import LabApp
>   File "C:\JupyterLab\resources\jlab_server\lib\site-packages\jupyterlab\labapp.py", line 15, in <module>
>     from jupyter_server.serverapp import flags
>   File "C:\JupyterLab\resources\jlab_server\lib\site-packages\jupyter_server\serverapp.py", line 42, in <module>
>     from jupyter_server.utils import run_sync_in_loop, urljoin, pathname2url
>   File "C:\JupyterLab\resources\jlab_server\lib\site-packages\jupyter_server\utils.py", line 23, in <module>
>     from tornado.httpclient import AsyncHTTPClient
>   File "C:\JupyterLab\resources\jlab_server\lib\site-packages\tornado\httpclient.py", line 42, in <module>
>     import ssl
>   File "C:\JupyterLab\resources\jlab_server\lib\ssl.py", line 98, in <module>
>     import _ssl             # if we can't import it, let the error propagate
> ImportError: DLL load failed while importing _ssl: The specified module could not be found.
> ```
> 
> It looks like OpenSSL DLL issue on your Windows installation. This might happen when anaconda is installed locally rather than globally (did you install JupyterLab Desktop for all users, or just for you?), when DLLs are missing or not in path.
> 
> Could you please check if the workaround of copying the DLL as described in [ContinuumIO/anaconda-issues#11994](https://github.com/ContinuumIO/anaconda-issues/issues/11994) solves this issue for you? If yes, we could add a script to do that during installation.
> 
> Another issue is that we need to allow opening links to GitHub because it looks the button "Report issue" gets:
> 
> ```
> [2021-12-23 21:05:50.748] [warn]  Navigation is not allowed; attempted navigation to: https://github.com/login?return_to=%2Fjupyterlab%2Fjupyterlab-desktop%2Fissues%2Fnew
> ```

I encountered exactly the same issue. This is a workaround except that you also need to copy `libcrypto-1_1-x64.dll`.
The same issue happened when importing sqlite3.
Therefore, I just copy every .dll file under `[env path]/Library/bin` to `[env path]/DLLs` to save time.

**Comment by marshlands2048** [comment] 2021-12-27 13:09
Thank you for the tips! I’ll try this workaround later.

**Comment by aqua0906** [comment] 2022-01-03 06:40
Unable to start jupyterlab.

A window is displayed.
![setPythonEnvironment](https://user-images.githubusercontent.com/377507/147904824-48af8548-7fb7-4b76-88e3-d5b1736e78bf.png)

Such a log remains in main.log.
[2022-01-03 15:35:20.077] [info]  Logging to file (C:\Users\******\AppData\Roaming\jupyterlab-desktop\logs\main.log) at 'false' level
[2022-01-03 15:35:20.128] [error] (node:1080) DeprecationWarning: findLogPath() is deprecated and will be removed in v5.
(Use `JupyterLab --trace-deprecation ...` to show where the warning was created)
[2022-01-03 15:35:22.236] [error] (node:1080) electron: The default of nativeWindowOpen is deprecated and will be changing from false to true in Electron 15.  See https://github.com/electron/electron/issues/28511 for more information.

**Comment by marshlands2048** [comment] 2022-01-05 08:52
I will try this.

**Comment by marshlands2048** [comment] 2022-01-05 08:54
> > Thank you for reporting this issue. The log file includes the following:
> > ```python
> > [2021-12-23 20:46:54.243] [info]  Jupyter Server initialization message: Traceback (most recent call last):
> >   File "C:\JupyterLab\resources\jlab_server\lib\runpy.py", line 185, in _run_module_as_main
> >     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
> >   File "C:\JupyterLab\resources\jlab_server\lib\runpy.py", line 144, in _get_module_details
> >     return _get_module_details(pkg_main_name, error)
> >   File "C:\JupyterLab\resources\jlab_server\lib\runpy.py", line 111, in _get_module_details
> >     __import__(pkg_name)
> >   File "C:\JupyterLab\resources\jlab_server\lib\site-packages\jupyterlab\__init__.py", line 7, in <module>
> >     from .labapp import LabApp
> >   File "C:\JupyterLab\resources\jlab_server\lib\site-packages\jupyterlab\labapp.py", line 15, in <module>
> >     from jupyter_server.serverapp import flags
> >   File "C:\JupyterLab\resources\jlab_server\lib\site-packages\jupyter_server\serverapp.py", line 42, in <module>
> >     from jupyter_server.utils import run_sync_in_loop, urljoin, pathname2url
> >   File "C:\JupyterLab\resources\jlab_server\lib\site-packages\jupyter_server\utils.py", line 23, in <module>
> >     from tornado.httpclient import AsyncHTTPClient
> >   File "C:\JupyterLab\resources\jlab_server\lib\site-packages\tornado\httpclient.py", line 42, in <module>
> >     import ssl
> >   File "C:\JupyterLab\resources\jlab_server\lib\ssl.py", line 98, in <module>
> >     import _ssl             # if we can't import it, let the error propagate
> > ImportError: DLL load failed while importing _ssl: The specified module could not be found.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It looks like OpenSSL DLL issue on your Windows installation. This might happen when anaconda is installed locally rather than globally (did you install JupyterLab Desktop for all users, or just for you?), when DLLs are missing or not in path.
> > Could you please check if the workaround of copying the DLL as described in [ContinuumIO/anaconda-issues#11994](https://github.com/ContinuumIO/anaconda-issues/issues/11994) solves this issue for you? If yes, we could add a script to do that during installation.
> > Another issue is that we need to allow opening links to GitHub because it looks the button "Report issue" gets:
> > ```
> > [2021-12-23 21:05:50.748] [warn]  Navigation is not allowed; attempted navigation to: https://github.com/login?return_to=%2Fjupyterlab%2Fjupyterlab-desktop%2Fissues%2Fnew
> > ```
> 
> I encountered exactly the same issue. This is a workaround except that you also need to copy `libcrypto-1_1-x64.dll`. The same issue happened when importing sqlite3. Therefore, I just copy every .dll file under `[env path]/Library/bin` to `[env path]/DLLs` to save time.

I do not know where the DLL file is.

**Comment by krassowski** [comment] 2022-01-06 17:47
> I do not know where the DLL file is.

What about `C:\JupyterLab\resources\jlab_server\Library\bin`? You would need to copy it to `C:\JupyterLab\resources\jlab_server\DLLs`.

I don't have a Windows at hand, but it should be about it.

**Comment by meeseeksmachine** [comment] 2022-01-06 17:52
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/how-to-solve-jupyter-server-initialization-failed/12469/2

**Comment by irgolic** [comment] 2022-01-06 21:33
Tried the suggested solution, same error – log now reports:

`ImportError: DLL load failed while importing error: The specified module could not be found.`

**Comment by black-snow** [comment] 2022-01-11 11:50
Landing here after an upgrade. I chose to install JupyerLabDesktop on a different disk. Now apparently the python stuff was install on the other disk (`F:`) but the Jupyter stuff was still installed on `C:`? Why's that. When I tell him to use the bundled python he says he can't find it under `C:\JupyterLabe\resources\...`, when I select the `python.exe` that was installed under `F:` I get the exact same screen as the OP.

Btw, the "report issue" should not pop open a browser window within Jupyter but just trigger the default browser. It doesn't even have an address bar such that I could copy the URL :/

**Comment by anis-2020** [comment] 2022-01-18 16:45
Hey guys, I have the same issue. I've spent hours today going through github and all these threads. I've copied all the dlls to the folders you mentioned and still the same error. My log is attached. Appreciate if someone can help me out. Running windows 11. 

FYI I'm a beginner at coding so please explain what to do step by step :)

Thanks.


[main.log](https://github.com/jupyterlab/jupyterlab-desktop/files/7890874/main.log)

**Comment by tomo-fujii** [comment] 2022-01-24 04:45
I had the same problem, but in my case, when I ran JupyterLab_app from the shortcut with "Run as administrator.", I was able to solve the problem.

**Comment by noah004B** [comment] 2022-02-08 01:32
I'm facing the same issue.

```
[2022-01-18 17:32:44.278] [info]  Jupyter Server initialization message: Traceback (most recent call last):
  File "C:\JupyterLab\resources\jlab_server\lib\runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\JupyterLab\resources\jlab_server\lib\runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\JupyterLab\resources\jlab_server\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\JupyterLab\resources\jlab_server\lib\site-packages\jupyterlab\__init__.py", line 7, in <module>
    from .labapp import LabApp
  File "C:\JupyterLab\resources\jlab_server\lib\site-packages\jupyterlab\labapp.py", line 15, in <module>
    from jupyter_server.serverapp import flags
  File "C:\JupyterLab\resources\jlab_server\lib\site-packages\jupyter_server\serverapp.py", line 42, in <module>
    from jupyter_server.utils import run_sync_in_loop, urljoin, pathname2url
  File "C:\JupyterLab\resources\jlab_server\lib\site-packages\jupyter_server\utils.py", line 23, in <module>
    from tornado.httpclient import AsyncHTTPClient
  File "C:\JupyterLab\resources\jlab_server\lib\site-packages\tornado\httpclient.py", line 42, in <module>
    import ssl
  File "C:\JupyterLab\resources\jlab_server\lib\ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: DLL load failed while importing _ssl: The specified module could not be found.
```

The workaround that copying `libcrypto-1_1-x64.dll` from `C:\JupyterLab\resources\jlab_server\Library\bin` to `C:\JupyterLab\resources\jlab_server\DLLs` is not working for me.

**Comment by Tuba202** [comment] 2022-02-12 23:50
Yep, the DLL move fix isn't working for me either...

**Comment by trdunsworth** [comment] 2022-02-13 19:00
I'm getting a similar issue. I gave it an installation path of D:\JupyterLab instead of the C drive and I'm getting the Error: Jupyter Server process terminated before the initialization completed error. I noticed when it tried to find python.exe it defaulted to a path on the C drive anyway. It also couldn't accept a Python 3.10 executable either.

**Comment by 3roqlu** [comment] 2022-02-18 23:58
I encountered the same problem, after a conda update. With a clean install it is working.

**Comment by asteppke** [comment] 2022-02-22 13:19
So the issue is that python has its internal search path (`sys.path`) where it looks for modules. Additionally when using binary packages that load DLL files on Windows a different search is started. Here as one of the paths searched are all the entries in the environment variable `PATH` (accessible e.g., via `os.environ['PATH']`):

````
C:\JupyterLab\resources\jlab_server>python
Python 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:22:46) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.environ['PATH']
[does not contain Library\bin]
````

This by default does not contain the `Library\bin` subdirectory where the DLL files are located. When using the underlying conda machinery, i.e. `activate.bat` in the Scripts directory, then this directory is explicitly added to `PATH`. 

So before the fix (https://github.com/jupyterlab/jupyterlab-desktop/pull/404) is released one can manually run in the command line the activate batch file followed by starting jupyterlab:
````
C:\JupyterLab>.\resources\jlab_server\Scripts\activate.bat
(base) C:\JupyterLab>JupyterLab
````

**Comment by jmakov** [comment] 2022-03-01 12:34
Same problem with v3.2.9-1 on Ubuntu 21.10 after fresh install (followed uninstall instructions).

**Comment by anaximeno** [comment] 2022-03-02 19:45
I am having the same problem on a computer with Linux Mint 20.3 Una (base Ubuntu LTS 20.04). This problem happened after I killed some Jupyter processes that were still running in the background after I closed the jupyterlab-desktop app. I thought there was some problem with the processes that were running in the background because they were still running after closing the app and they were using a great piece of my RAM, so I decided to eliminate them. But when I tried to open again the environment that was running at the time I got this error:

```bash
[2022-03-02 18:04:37.445] [warn]  Error: Jupyter Server process terminated before the initialization completed
    at ChildProcess.<anonymous> (/opt/JupyterLab/resources/app.asar/build/out/main/server.js:205:28)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
```

I'll try to analyze if it happens with different environments and if I can find the root of this problem.

**Comment by anaximeno** [comment] 2022-03-02 20:13
I created another Conda environment and tried to launch the app in that environment. It worked well in the first use, but after closing the app and trying to reopen I had the same error message again. So I believe that eliminating the processes wasn't the reason for the problem before.

**Comment by black-snow** [comment] 2022-03-03 14:22
`3.2.9-1` seems to work fine again

**Comment by Okaforemeka** [comment] 2022-04-01 17:05
Could someone Ps support me with the resolution of this issue, I updated jupyterlab from v3.3.2-1 to v3.3.2-2 and haven't been able to launch jupyterlab anymore. 
The following error screen pops up. 
I have also attached a copy of my log file to clarify the issue.

Thanks in advance.


![Screenshot 2022-04-01 180206](https://user-images.githubusercontent.com/57918394/161309630-ebbce257-62e1-4f0b-a42e-f8cd81a05376.jpg)
[main.log](https://github.com/jupyterlab/jupyterlab-desktop/files/8399677/main.log)

**Comment by anaximeno** [comment] 2022-04-01 17:45
@Okaforemeka Are you trying to open it on a extern environment or the default bundled environment?

**Comment by Okaforemeka** [comment] 2022-04-01 17:53
Hi @anaximeno, thanks for reaching out. I am using the default bundled environment.

**Comment by Okaforemeka** [comment] 2022-04-01 18:09
@anaximeno yes I did, Its not my first time updating jupyterlab successfully. However im  surprised I now get the same error when I go reinstall the the previous version (v3.3.2-1 ). Not sure why this strange error.

**Comment by harripj** [comment] 2022-04-01 21:54
I'd like to add that on MacOS I do not receive this error when launching the app by clicking the app icon.

If I launch from the terminal, ie. `jlab`, then I get the error in the OP. To solve this I had to deactivate `conda` and then run `jlab`, so this is issue may be environment based, at least partially.

**Comment by Okaforemeka** [comment] 2022-04-01 22:18
I deactivated conda but still get the same error screen. 

My log file also gets updated with the same repeat error lines below:

[2022-04-01 23:12:56.134] [info]  In production mode
[2022-04-01 23:12:56.137] [info]  Logging to file (C:\Users\Okaforemeka\AppData\Roaming\jupyterlab-desktop\logs\main.log) at 'false' level
[2022-04-01 23:12:56.178] [error] (node:13776) DeprecationWarning: findLogPath() is deprecated and will be removed in v5.
(Use `JupyterLab --trace-deprecation ...` to show where the warning was created)
[2022-04-01 23:13:00.190] [warn]  Error: Jupyter Server process terminated before the initialization completed
    at ChildProcess.<anonymous> (C:\JupyterLab\resources\app.asar\build\out\main\server.js:279:28)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)


Support is kindly requested.

**Comment by mbektas** [comment] 2023-06-07 05:16
closing this. please retry with the latest version as there were many enhancements since these issues reported. create a new issue if needed.

**Closed by mbektas** 2023-06-07 05:16 UTC
Labels: bug
