### ISSUE TITLE
JupyterLab Desktop Does Not Save Custom Theme

### ISSUE THREAD

**Issue by OhanazzZ** [jupyterlab/jupyterlab-desktop#815] opened 2024-04-27 09:02 UTC
## Description

JupyterLab Desktop Does Not Save Custom Theme.
Have to re-select the custom theme every time

## Reproduce

Assuming you have a custom theme (if not, just download any one)

1. Set theme to custom theme
2. Close the app
3. Reopen the app
4. Theme is reset to the default dark theme, instead of the custom theme.

## Expected behavior

Hopefully the custom theme is preserved through sessions (instead of having to manually re-select the theme every time).

## Context

- Operating System and version: MacOS Sonoma 14.4.1
- JupyterLab-Desktop version: 4.1.5-1
- local jupyterlab version: 4.1.8

**Comment by OhanazzZ** [comment] 2024-05-01 07:48
Hi Jason,

Thanks for answering. 

Unfortunately it was not - I've seen that post and unchecked the sync option - and repeated the process of re-selecting the theme and restarting the app, 3 times.

FWIW, I also tried having the setting.json file open, and observed that: regardless of whether I change the theme within app, or add a line specifying the theme in the json file, once the app is closed and restarted, the setting.json just reset to its original state, everytime.

At that point I gave up trying and posted the issue, but yesterday I found it working as expected!

I can only think of 2 explanations:
1. Restarting the machine fixed this
2. or perhaps the way you open the notebook matter (i.e. directly from finder, open within jupyterlab, resume last open session etc)

**Comment by JasonWeill** [comment] 2024-05-07 16:55
@OhanazzZ Thank you very much for your follow up about this issue! Because it's no longer reproducible on your system, I'm going to close this issue. If you notice this issue or any other, please open a new issue in this project. I really appreciate your feedback!

**Closed by JasonWeill** 2024-05-07 16:55 UTC
Labels: bug, status:Needs Info, status:Needs Triage
