### ISSUE TITLE
Duplication in "manage python environments"

### ISSUE THREAD

**Issue by Bobson1729** [jupyterlab/jupyterlab-desktop#787] opened 2024-03-05 03:24 UTC
![image](https://github.com/jupyterlab/jupyterlab-desktop/assets/88941442/f13583fc-2120-4926-9dc1-ab8422f21666)

I have duplication in "manage python environments". I am not sure this is an issue with Jupyterlab Desktop, JupyterLab, miniconda, or something else.

Thanks for your help!

**Comment by JasonWeill** [comment] 2024-03-05 17:31
If you open a `conda`-enabled command prompt (e.g., Miniconda command prompt on windows), and you run `conda env list`, what do you see?

**Comment by mbektas** [comment] 2024-03-06 15:35
@Bobson1729 did you create any environments using JupyterLab Desktop? If so, did you use conda or venv type?

**Comment by Bobson1729** [comment] 2024-03-06 16:25
I didn't manually create any environments. The only one I have is "base" from miniconda. I installed Jupyterlab and Notebook from conda (conda-forge), and JLD via windows install.

All the duplicate environments in JLD environments all point to the exact same location (which is the base environment) and when I set one of them to default, they all say "default" .

conda env list only shows the base environment as well.

I did many reinstalls of jupyterlab, jupyter notebook, and jld to try and get the install right.

Is there a config file somewhere which lists the environments found by jld? Perhaps this just didn't clean up old info and every reinstall just added to this file instead of replacing it?

Again, thanks for your help!

**Comment by mbektas** [comment] 2024-03-06 17:11
thanks for the in @Bobson1729 . The issue is caused by multiple discoveries of the same environment and deduplication not working properly. [this change](https://github.com/jupyterlab/jupyterlab-desktop/commit/c3d66aec66582189ab34ae7aea49b42ba9ed8977) must have caused it.
I will work on a solution. other than showing duplicate entries, this shouldn't cause any real issues. are you having any problems launching JupyterLab sessions?

environments are stored in [application data](https://github.com/jupyterlab/jupyterlab-desktop/blob/master/user-guide.md#Configuration-and-data-files) file, but even if you delete the duplicate entries, app will rediscover and reduplicate at next launch.

**Comment by Bobson1729** [comment] 2024-03-06 17:12
Thanks! No issues on the functionality.

**Comment by mbektas** [comment] 2024-03-10 04:56
hi @Bobson1729 , I implemented a fix for this issue. could you test it using the PR build output [here](https://github.com/jupyterlab/jupyterlab-desktop/actions/runs/8219595657) before I publish it.

**Comment by Bobson1729** [comment] 2024-03-10 05:18
I would love to help, but I'm afraid I don't know how. I am very much a beginner here. Is there a way that you can compile a new "JupyterLab-Setup-Windows-x64.exe" installer for me?

**Comment by mbektas** [comment] 2024-03-10 05:23
@Bobson1729 the link I shared (scroll to bottom to Artifacts section) had a [link to latest installer](https://github.com/jupyterlab/jupyterlab-desktop/actions/runs/8219595657/artifacts/1312425681) with the fix. you can download and extract it and install. thanks!

**Comment by Bobson1729** [comment] 2024-03-10 05:37
@mbektas  Got it. Works great!
![image](https://github.com/jupyterlab/jupyterlab-desktop/assets/88941442/3d054c82-62f2-4c6e-9332-b467d4ef7a9f)

**Comment by mbektas** [comment] 2024-03-10 16:58
thanks for testing @Bobson1729 !

**Closed** 2024-03-10 16:58 UTC
Labels: bug
