### ISSUE TITLE
No output from running cells after installation on Windows

### ISSUE THREAD

**Issue by astroStudent123** [jupyterlab/jupyterlab-desktop#386] opened 2022-01-06 17:34 UTC
## Description

I installed on Windows using the instructions in the README file. Everything appears fine, except running cells produces no output; e.g. if I open a new notebook, create a code cell with the code print('here'), and click the "run the selected cells and advance" button, the curser advances but no output is produced. Re-installing doesn't fix this. 

## Reproduce

1. Download .exe file from https://github.com/jupyterlab/jupyterlab-desktop/blob/master/README.md
2. Install following setup prompts
3.  Open new notebook from the launcher
4.  Type any command that should produce output (e.g. a print statement)
5.  Click run cell 

## Expected behavior

Output should be produced but it isn't. The curser moves to the next cell but no output is produced. 

## Context

- Operating System and version: Windows 10 pro
- JupyterLab-Desktop version: Version 3.2.5-2
- Installer: .exe 

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the terminal inside of JupyterLab-Desktop here.
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.   

Try the new cross-platform PowerShell https://aka.ms/pscore6
PS C:\Users\Lea> jupyter troubleshoot                    
jupyter : The term 'jupyter' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the 
name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ jupyter troubleshoot
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (jupyter:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
PS C:\Users\Lea> 
![image](https://user-images.githubusercontent.com/90289357/148429523-ab15acf8-8077-4d80-a447-85d69f97e569.png)

Hmm... the terminal doesn't recognize this command. 

You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Browser Output (required for interface issues after loading)</summary>

<pre>
Paste the output from the DevTools JavaScript console here, if applicable.
 
![image](https://user-images.githubusercontent.com/90289357/148435364-afa5db72-a890-4e47-a10d-8808bebaf1f4.png)

</pre>
</details>

<details><summary>Logs (required for issues with loading, server and startup)</summary>

<pre>
Paste the logs from the mian.log file here.

C:\Users\<username>\AppData\Roaming\jupyterlab-desktop\logs  exists as a path, but main.log is not there.

</pre>
</details>

**Comment by krassowski** [comment] 2022-01-06 17:38
> JupyterLab-Desktop version: unsure (most recent version)

Please for to `Help` -> `About` to find the version.

Please provide the troubleshoot, browser and logs output. The details on how to get those are described in the template comments.

You can edit your posts on GtiHub instead of creating new issues (the Edit options is under '...' in the right corner of a post), ideally this would have been posted in https://github.com/jupyterlab/jupyterlab-desktop/issues/385 to avoid duplication, but no worries - we can work with that as long as you provide all the information which is necessary for us to help you. Help us help you.

**Comment by astroStudent123** [comment] 2022-01-06 18:25
Hi,
I have updated my issue, however I am not sure how helpful my responses are
since I could not find the browser or logs output. I apologize!

**Comment by krassowski** [comment] 2022-01-06 18:32
The console tab is here:

![console-circle](https://user-images.githubusercontent.com/5832902/148432556-be65511f-862c-4b5b-865f-ad4083eb3187.png)

> I cannot access this file. The %USERPROFILE%\AppData\Roaming\jupyterlab-desktop\logs\main.log filepath does not exist.

Could you try to look once again in similar paths? It might be in a slightly different path:
- because of differences between Windows versions
- because of differences between installations
- because there is a typo

`%USERPROFILE%` may correspond to `C:\Users\yourusername` - Windows should recognise this variable when you use it in command line.

**Comment by astroStudent123** [comment] 2022-01-06 18:56
Thanks! the main.log file is still not there though.

**Comment by krassowski** [comment] 2022-01-06 20:55
Thank you! Hmm... This is quite odd that the logs file was not created. It makes me think that maybe there is an issue with the rights to create files? Did you check "install for everyone" or "install only for me" (the wording in the installer is slightly different, I don't remember exactly of top of my head)? Would you mind trying to run as administrator?

Could you also check the Network tab in the developer tools for any errors?

**Comment by astroStudent123** [comment] 2022-01-06 21:40
Here is the network tab
[image: image.png]
By "run as administrator", do you mean open with sudo jlab --verbose 4 from
the command line? Is there a way to check whether I installed for everyone
or only me without reinstalling?

**Comment by PhilipTsv** [comment] 2022-01-07 16:39
I can confirm this as an issue. I forgot to uninstall the server first and uninstalled the JL app firsts and then when I was installing the new version I clicked on "install for all users", but then reinstalled with "install only for myself" not sure if any of those things is the cause. When I run a cell the kernel starts, but then instead of running the cell it seems to just shutdown itself.

**Comment by astroStudent123** [comment] 2022-01-10 17:17
Hi,
Any updates on this?

Thanks,
Leah

**Comment by PhilipTsv** [comment] 2022-01-10 17:47
@astroStudent123,
I'm not sure if there is any progress on this, but if you need to use JupyterLab for a project, I'd suggest downloading a previous version as I did.
Cheers,
Philip

**Comment by aravindh-krishnamoorthy** [comment] 2022-01-13 12:36
@PhilipTsv @astroStudent123  Check if the workaround in #388 helps you. In my case, double clicking on the desktop shortcut resulted in no outputs from the cells. But, activating conda and then starting jlab as in #388 worked.

**Comment by astroStudent123** [comment] 2022-01-17 21:49
Hi,
Actually, it looks like while that solution worked the first time, when I
try to launch JupyterLab the same way again it doesn't work.
The first time (a few days ago) that I ran:

C:\JupyterLab\resources\jlab_server\condabin\activate

jlab .


It opened successfully. But now when I run the activate command, I get:
[image: image.png]


If I try just running the jlab command without the activate command first,
a dialog box pops up asking me to select the Python environment to use, but
when I select "Use the bundled Python environment", click "save and
restart," the dialog box simply pops up again in an endless cycle. I could
try "Use custom Python environment, but I am not sure how to do that.
[image: image.png]




<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by mbektas** [comment] 2023-02-26 19:50
@astroStudent123 can you test with the latest version 3.6.1-2 and update if you still have problems?

**Comment by mbektas** [comment] 2023-06-07 05:17
closing since no update

**Closed by mbektas** 2023-06-07 05:17 UTC
Labels: bug
