### ISSUE TITLE
Random zoom and can't restore the default.

### ISSUE THREAD

**Issue by A3EKV** [jupyterlab/jupyterlab-desktop#271] opened 2021-10-01 13:36 UTC
Hello,
I am running the latest version of this application on Ubuntu 20.04.
I have experienced several times the following issue (I don't know how to reporoduce it but all I know is that it occurs randomly when I switch to use another application such as VLC, browser, etc. and switch back to jupyterLab application, the content get zommed as shown below:

![image](https://user-images.githubusercontent.com/90999345/135629006-8fcae95d-3d3a-4580-88b1-eb038492c26b.png)

As I have mentioned above, I don't know exactly how to reproduce it, but the workaround that I am looking for now, at least, is how to reset the view, to the default. It's extremely annoying. 

I have to restart the application several times (maybe 3 or more times) in order to get the default view. Here is the default normal view:

![image](https://user-images.githubusercontent.com/90999345/135629582-2d395d12-70b3-4aba-91f3-6eaf41021e48.png)

Thank you

**Comment by krassowski** [comment] 2021-10-01 20:41
Have you tried using <kbd>Ctrl</kbd> + <kbd>-</kbd> and <kbd>Ctrl</kbd> + <kbd>+</kbd> to adjust the zoom instead of restarting the application?

**Comment by A3EKV** [comment] 2021-10-01 20:48
@krassowski 
Yes, I have tried that and `ctrl` + mouse wheel scroll but nothing changes.

**Comment by krassowski** [comment] 2021-10-01 20:49
Please try <kbd>Ctrl</kbd> + <kbd>-</kbd> and <kbd>Ctrl</kbd> + <kbd>+</kbd>. Mouse wheel scroll indeed is not connected to zoom. I checked that it works on Ubuntu for me, it should work for you too.

**Comment by krassowski** [comment] 2021-10-01 20:50
The next question would be:

>  have experienced several times the following issue (I don't know how to reporoduce it but all I know is that it occurs randomly when I switch to use another application such as VLC, 

how do you switch to another application? Is this possible that you have a keybinding conflict that triggers an equivalent of <kbd>Ctrl</kbd> + <kbd>+</kbd>?

**Comment by A3EKV** [comment] 2021-10-01 20:51
@krassowski : No, it doesn't work. I have just tried that now, neither` Ctrl `+ `-` nor `Ctrl` + `+` work

**Comment by A3EKV** [comment] 2021-10-01 20:52
> how do you switch to another application? Is this possible that you have a keybinding conflict that triggers an equivalent of Ctrl + +?

Only using the mouse without any keyboard shortcuts.

**Comment by krassowski** [comment] 2021-10-01 20:54
Thanks for the extra info! I guess we will need to wait for someone else to give another data points as it does not seem reproducible (on Ubuntu 21.04). Would you mind also mentioning which version (including the -x part) you have installed please?

**Comment by A3EKV** [comment] 2021-10-01 20:56
I am using an AZERTY keyboard.I have noticed that using the + and - signs from the numpad doesn't work with Ctrl. But ONLY when I press `Ctrl ``Shift` `=` it zooms in but can't zoom in using `Ctrl ``-` (from the row on top).

**Comment by A3EKV** [comment] 2021-10-01 21:01
Now I can't undo the zoom and the application is not usable:

![image](https://user-images.githubusercontent.com/90999345/135685632-2eac1f11-ec87-409d-a153-b1f92b0451bd.png)

**Comment by krassowski** [comment] 2021-10-01 21:02
I can confirm that <kbd>ctrl</kbd> <kbd>+</kbd> /<kbd>-</kbd> does not work when using +/- from numpad.

**Comment by krassowski** [comment] 2021-10-01 21:04
<kbd>ctrl</kbd> + <kbd>0</kbd> should reset zoom too (but again not from numpad).

**Comment by A3EKV** [comment] 2021-10-01 21:08
@krassowski : Thanks! 
`Ctrl ` `0` doesn't work (both numpad nor from the top row) I have tried `Ctrl ` `Shift` `0` , etc. still doesn't work.

**Comment by krassowski** [comment] 2021-10-01 21:12
Interesting. I imagine we could add "reset zoom" in:

https://github.com/jupyterlab/jupyterlab_app/blob/474561c509ce17827c1a912d33e3e424da2c6a7d/src/main/shortcuts.ts#L98-L169

to make sure this is available (but I don't know why it works ok for me right now but it does not work for you).

**Comment by A3EKV** [comment] 2021-10-01 21:18
This is strange since the most keyboard shortcuts such as `Ctrl` `0`, etc. you mentionned so far work on the browser.

**Comment by A3EKV** [comment] 2021-10-01 21:24
Another strange behaviour is that when I open the Matplotlib reference from the `Help` menu, it opens zoomed to a high level and there is no way to decrease that even after restarting.

**Comment by A3EKV** [comment] 2021-10-02 09:38
Update: I have added "US English" Keyboard to my system, and can reset the view using `Ctrl ` `0` (0 from the top row not from the numpad).

**Comment by mbektas** [comment] 2023-02-26 19:44
@A3EKV is this still an issue with the latest version 3.6.1-2?

**Comment by mbektas** [comment] 2023-06-07 05:11
closing since no update for long

**Closed by mbektas** 2023-06-07 05:11 UTC
Labels: bug
