### ISSUE TITLE
jlab command does not work on Apple silicon Mac

### ISSUE THREAD

**Issue by fjhickernell** [jupyterlab/jupyterlab-desktop#656] opened 2023-05-15 23:01 UTC
I installed Jupyter Lab Desktop and upgraded jupyter-lab to version 4.0 on my two Macs.  On the Intel silicon Mac typing jlab in the VS code terminal launches the desktop app, but on the Apple silicon Mac typing jlab gives me a  command not found: jlab error

**Comment by JasonWeill** [comment] 2023-05-16 16:44
Resolving as a duplicate of #655; it was previously reported that the `jlab` command isn't in the `PATH` by default, requiring one to set up a symlink manually (this is a bug).

**Closed by JasonWeill** 2023-05-16 16:44 UTC
Labels: status:Needs Triage
