### ISSUE TITLE
How to install Git?

### ISSUE THREAD

**Issue by chbussler** [jupyterlab/jupyterlab-desktop#287] opened 2021-10-08 14:51 UTC
I want to install https://github.com/jupyterlab/jupyterlab-git, but am unsure on how to approach this. Would it be possible to add some instructions to the readme? Thank you.

**Comment by hellojinwoo** [comment] 2021-10-09 09:15
Installing additional JupyterLab Extensions are not supported in the desktop application at the moment. We are considering adding this support in a future release. - Referenced from other questions

**Comment by krassowski** [comment] 2021-10-09 12:45
I think that this is a duplicate of https://github.com/jupyterlab/jupyterlab-desktop/issues/264. Opening fewer duplicate issues helps prioritize work rather than answering duplicates ;)

**Closed** 2021-10-09 13:33 UTC
Labels: bug, duplicate
