### ISSUE TITLE
How do I change which Python is used?

### ISSUE THREAD

**Issue by AndrewChap** [jupyterlab/jupyterlab-desktop#169] opened 2018-10-18 21:10 UTC
My apologies if this is not specific to Jupyterlab App.

in a notebook within Jupyterlab App, when I run:
```
import sys
sys.executable
```
it returns
`'/usr/bin/python3'`

I would like it to return 
`'/usr/local/anaconda3/bin/python'`

How do I specify which python Jupyterlab App uses?

Thank you!

**Comment by sbliven** [comment] 2021-09-22 15:53
This is a pretty important feature. I need to access kernels from my system miniconda installation. Currently (at least on MacOS) I don't see any options to import these, since the installer creates its own conda installation.

**Comment by eduardobonet** [comment] 2021-09-22 17:31
On MacOS, I can add new kernels by adding them to the `~/Library/Jupyter/kernels` folder (https://jupyter-client.readthedocs.io/en/stable/kernels.html)

**Comment by westurner** [comment] 2021-09-22 22:29
Environments should be built with repo2docker or at least REES: Reproducible Execution Environment Specification IMHO. That adds a container system dependency, but it's cross platform and reproducible.

I put together some notes for an "nbhandler" app awhile back:
https://github.com/westurner/nbhandler/issues/1

> Launch a notebook server locally from a link or a downloaded file; like BinderHub for the desktop

> [...] https://github.com/machine-learning-apps/repo2docker-action is a GitHub Action that runs repo2docker and uploads to dockerhub. This is useful for projects that don't need to be built by end users if there's already an image to just pull

**Comment by westurner** [comment] 2021-09-22 22:32
To discover local conda envs, nb_conda_kernels works. From https://github.com/Anaconda-Platform/nb_conda_kernels :

> nb_conda_kernels
> This extension enables a Jupyter Notebook or JupyterLab application in one conda environment to access kernels for Python, R, and other languages found in other environments. When a kernel from an external environment is selected, the kernel conda environment is automatically activated before the kernel is launched. This allows you to utilize different versions of Python, R, and other languages from a single Jupyter installation.
>
> The package works by defining a custom KernelSpecManager that scans the current set of conda environments for kernel specifications. It dynamically modifies each KernelSpec so that it can be properly run from the notebook environment. When you create a new notebook, these modified kernels will be made available in the selection list.

**Comment by krassowski** [comment] 2021-09-25 13:32
There is also https://github.com/Cadair/jupyter_environment_kernels but I do not know if it is still maintained. I would be love to see this effort rebooted so we can use any environment in the JupyterLab-App.

**Comment by sbliven** [comment] 2021-10-05 19:26
I got jupyterlab.app to recognize my existing jupyter environments! As @westurner mentioned, this requires installing nb_conda_kernels to the jupyterlab base environment. However, it's a bit tricky on macOS since that environment is installed as root by default. I ran the following commands in a terminal:

```bash
source /Applications/JupyterLab.app/Contents/Resources/jlab_server/bin/activate
conda info  #ensure the right environment is loaded
sudo conda install nb_conda nb_conda_kernels
```

After restarting jupyter all conda environments were available as kernels.

**Comment by krassowski** [comment] 2021-10-07 17:00
@mbektas would it be a good idea to include `nb_conda_kernels` in the installer?

**Comment by shayandavoodii** [comment] 2021-10-07 17:09
> I got jupyterlab.app to recognize my existing jupyter environments! As @westurner mentioned, this requires installing nb_conda_kernels to the jupyterlab base environment. However, it's a bit tricky on macOS since that environment is installed as root by default. I ran the following commands in a terminal:
> 
> ```shell
> source /Applications/JupyterLab.app/Contents/Resources/jlab_server/bin/activate
> conda info  #ensure the right environment is loaded
> sudo conda install nb_conda nb_conda_kernels
> ```
> 
> After restarting jupyter all conda environments were available as kernels.

@krassowski Hi again.
I got stuck at this point ["... this requires installing nb_conda_kernels to the jupyterlab base environment."](https://github.com/jupyterlab/jupyterlab_app/issues/169#issuecomment-934708235) for windows 10.

**Comment by shayandavoodii** [comment] 2021-10-07 17:12
> source C:\JupyterLab\resources\jlab_server\bin\activate

i should run them in a cell in jupyterlab app?

**Comment by shayandavoodii** [comment] 2021-10-07 17:41
> What about trying without `bin\activate` at the end?
> 
> ```
> activate C:\JupyterLab\resources\jlab_server
> ```
> 
> or
> 
> ```
> activate C:/JupyterLab/resources/jlab_server
> ```

Yessss. Thanks @krassowski !!!
So here is the steps for Windows Users:
1. Run Anaconda Prompt as administrator
2. run this command: `activate C:/JupyterLab/resources/jlab_server`
3. run this command: `conda install nb_conda nb_conda_kernels`
4. then run the jupyterlab app :)

**Comment by shayandavoodii** [comment] 2021-11-16 07:18
Hello again @krassowski !
hope you doing perfectly well!
Thanks to JupyterLab Desktop `3.2.3-1`, now i can use my custom conda env in JupyterLab desktop (on WINDOWS 10).
here are steps that I made :
+ open Anaconda Prompt
    - `conda activate <NAME_OF_CONDA_ENV>`
    - `conda install jupyterlab`
+ open JupyterLab desktop **v3.2.3-1**
+ follow instructions in [Changing the Python Environment used by JupyterLab Desktop](https://github.com/jupyterlab/jupyterlab-desktop/blob/master/user-guide.md#changing-the-python-environment-used-by-jupyterlab-desktop).

Thanks a lot!! 🥳

**Comment by AndrewAmmerlaan** [comment] 2021-11-16 07:43
Works for me too now, on Gentoo Linux :partying_face: 

What would be awesome is if we could also specify the python env on the command line, e.g. `jupyterlab-desktop --python-env /usr/bin/python3.9`

**Comment by krassowski** [comment] 2021-11-20 19:48
Thank you all for confirming that it works well. It is really good to get such confirmation from users using different platforms.

As mentioned above, JupyterLab Desktop [v3.2.3-1](https://github.com/jupyterlab/jupyterlab-desktop/releases/tag/v3.2.3-1) added support for changing environments from the GUI (a selector on the status bar), including using a custom conda environment.

The instructions are currently available in the user guide: https://github.com/jupyterlab/jupyterlab-desktop/blob/master/user-guide.md#changing-the-python-environment-used-by-jupyterlab-desktop

I will close this one as resolved, but please do feel welcome to open issues with other suggestions/feature requests or if something is not working well.

**Closed by krassowski** 2021-11-20 19:48 UTC
