### ISSUE TITLE
Windows installer - missting sign certificate

### ISSUE THREAD

**Issue by donhuvy** [jupyterlab/jupyterlab-desktop#660] opened 2023-05-27 15:23 UTC
![image](https://github.com/jupyterlab/jupyterlab/assets/1328316/1a232d74-d6f2-4364-8ef1-14bdcc7f5f07)

![image](https://github.com/jupyterlab/jupyterlab/assets/1328316/6da1408f-40dc-4063-a6e3-c83da5829c11)

![image](https://github.com/jupyterlab/jupyterlab/assets/1328316/adea5f00-cb4e-4fcd-acbd-cb8426b81462)

**Comment by krassowski** [comment] 2023-05-28 10:39
I've transferred this to jupyterlab-desktop repository. This is a duplicate of https://github.com/jupyterlab/jupyterlab-desktop/issues/202 with most recent update a month ago in another duplicate: https://github.com/jupyterlab/jupyterlab-desktop/issues/648#issuecomment-1527692946.

**Closed** 2023-05-28 15:48 UTC
Labels: bug, status:Needs Triage
