### ISSUE TITLE
Change the terminal from Windows Powershell to Bash

### ISSUE THREAD

**Issue by yuliaUU** [jupyterlab/jupyterlab-desktop#643] opened 2023-04-23 22:25 UTC
Hi! I have set that the default terminal on my Windows PC is bash terminal. If I launch Jupyter lab online 
![image](https://user-images.githubusercontent.com/54612866/233869353-e818b785-5c62-45c2-abab-8d3922c917c5.png)
it opens it with terminal that is bash:
![image](https://user-images.githubusercontent.com/54612866/233869383-cc028145-3c36-405b-af53-9a40128d74b5.png)

however in desktop version, the terminal is still Windows powershell:
![image](https://user-images.githubusercontent.com/54612866/233869403-34059997-bcc8-4f31-b675-f042e89423a2.png)

How can I change it to bash terminal?

**Comment by JasonWeill** [comment] 2023-04-25 16:35
Resolving as duplicate of #309.

**Closed by JasonWeill** 2023-04-25 16:35 UTC
Labels: bug, duplicate, status:Needs Triage
